name: Publish
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.6

      - name: Setup node for publication
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@bemedev'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 10s
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - uses: JS-DevTools/npm-publish@v3
        id: publish
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          strategy: upgrade

      - name: Check - updated
        if: ${{ steps.publish.outputs.type }}
        run:
          echo "${{ steps.publish.outputs.name }} Version changed from ${{
          steps.publish.outputs.old-version }} to ${{
          steps.publish.outputs.version }}"

      - name: Check - not updated
        if: ${{ ! steps.publish.outputs.type }}
        run: echo "Remain the same! - ${{ steps.publish.outputs.version }}"
